### ISSUE TITLE
UserStory 14

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#26]
As a User i want to be able to switch to darkmode
to save energy while using the app

Description

![Image](https://user-images.githubusercontent.com/115098194/232741593-c7d18f1a-3fd0-403c-8162-aaedb3a9e4d6.png)

Acceptance Criteria:

- [ ] root index page got link to options
- [ ] options menu got a possibility to toggle darkmode
- [ ] darkmode is toggling style

**Comment by PacoSchwab** [comment]
LGTM, nice feature!
